model_config:
  name: bilstm
  char_embedding_dim: 256
  rnn_cell_dim: 256
  rnn_n_layers: 1
  dropout: 0.0
  use_residual: False


learning_config:
  dataset_config:
    max_chars_in_sentence: 200
    take_num_top_chars: 50

  optimizer_config:
    learning_rate: 1e-4
    beta_1: 0.9
    beta_2: 0.999
    epsilon: 1e-7

  running_config:
    batch_size: 128
    num_epochs: 10